### ISSUE TITLE
Version 1.0.9 cannot be installed on windows

### ISSUE THREAD

**Issue by marcomd** [eventmachine/eventmachine#675]
Ruby 2.2.3 x64 patch 173 
Devkit 4.7.2 x64
Windows 7 

**project.h:116:25: fatal error: openssl/ssl.h: No such file or directory**

I don't know which operation goes wrong, ruby (from rubyinstaller.org) have openssl in:

lib\ruby\2.2.0\x64-mingw32\openssl.so

Any idea?

```
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
Successfully installed websocket-driver-0.6.3
Fetching: eventmachine-1.0.9.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing volt:
        ERROR: Failed to build gem native extension.

    current directory: C:/ruby/ruby-223x64p173volt/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9/ext
C:/ruby/ruby-223x64p173volt/bin/ruby.exe -r ./siteconf20160113-8340-1vih5ql.rb extconf.rb
checking for main() in -lssleay32... no
checking for main() in -lssleay32... no
checking for main() in -lssleay32... no
checking for main() in -lssleay32... no
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... no
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for pipe2() in unistd.h... no
checking for accept4() in sys/socket.h... no
checking for SOCK_CLOEXEC in sys/socket.h... no
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for windows.h... yes
checking for winsock.h... yes
checking for main() in -lkernel32... yes
checking for main() in -lrpcrt4... yes
checking for main() in -lgdi32... yes
checking for clock_gettime()... yes
checking for CLOCK_MONOTONIC_RAW in time.h... no
checking for CLOCK_MONOTONIC in time.h... yes
CXXFLAGS=$(cxxflags) -Wall -Wextra -Wno-deprecated-declarations -Wno-ignored-qua
lifiers -Wno-unused-result -Wno-address
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can
 be found here:

  C:/ruby/ruby-223x64p173volt/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/e
ventmachine-1.0.9/mkmf.log

current directory: C:/ruby/ruby-223x64p173volt/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9/ext
make "DESTDIR=" clean

current directory: C:/ruby/ruby-223x64p173volt/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9/ext
make "DESTDIR="
generating rubyeventmachine-x64-mingw32.def
compiling binder.cpp
In file included from binder.cpp:20:0:
project.h:116:25: fatal error: openssl/ssl.h: No such file or directory
compilation terminated.
make: *** [binder.o] Error 1

make failed, exit code 2

Gem files will remain installed in C:/ruby/ruby-223x64p173volt/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9 for inspection.
Results logged to C:/ruby/ruby-223x64p173volt/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/eventmachine-1.0.9/gem_make.out
```

from file mkmf.log:
```
package configuration for openssl is not found
have_library: checking for main() in -lssleay32... -------------------- no
```

**Comment by Eric-Guo** [comment]
Same problem, can confirm cause by #668 because if I reverse it, can compile in Windows.

**Comment by marcomd** [comment]
Could i suggest to yank 1.0.9 gem till it will be resolved?

**Comment by sodabrew** [comment]
Corrected in 1b8edb94f04f456d70c1b8ac95b5a314f162c98d I will post a 1.0.9.1 today. There is an issue reported in https://github.com/eventmachine/eventmachine/issues/671#issuecomment-171236217 that I want to chase down if possible -- if you do compile `--with-ssl-dir=C:/OpenSSL` (or equivalent for your system) does it fail with a different error?

**Comment by sodabrew** [comment]
I've just posted EventMachine 1.0.9.1, please give it a try!

**Comment by marcomd** [comment]
It works :+1: 
Thank you!

**Comment by MarkSummers** [comment]
This still fails when installed as a dependency of a Vagrant plugin e.g.

`vagrant plugin install landrush` 

...on Windows 10.

```
package configuration for openssl is not found
have_library: checking for main() in -lssleay32... -------------------- no

"gcc -o conftest.exe -I"C:/Program Files (x86)/HashiCorp/Vagrant/embedded/include/ruby-2.2.0/i386-mingw32" -I"C:/Program Files (x86)/HashiCorp/Vagrant/embedded/include/ruby-2.2.0"/ruby/backward -I"C:/Program Files (x86)/HashiCorp/Vagrant/embedded/include/ruby-2.2.0" -I. -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -L"C:/Program Files (x86)/HashiCorp/Vagrant/embedded/lib" -L.      -lmsvcrt-ruby220  -lssleay32 -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
conftest.c: In function 't':
conftest.c:16:32: warning: variable 'p' set but not used [-Wunused-but-set-variable]
c:/program files (x86)/hashicorp/vagrant/embedded/mingw/bin/../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lssleay32
collect2.exe: error: ld returned 1 exit status
```

**Comment by NeoLegends** [comment]
Doesn't work on my machine. :/

**Comment by sodabrew** [comment]
Please post enough information so that I can help?

**Comment by NeoLegends** [comment]
Oh, sorry. I've got almost the same error as @marcomd. This is the output: http://pastebin.com/YFfKJSpc
